{{- if .Values.ingress.tls.crt }}
{{- if .Values.ingress.tls.key }}
apiVersion: v1
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt }}
  tls.key: {{ .Values.ingress.tls.key }}
kind: Secret
metadata:
  name: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "fullname" .)) }}
{{- end }}
{{- end }}