apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}
  annotations: {}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "appname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/application-secrets: "{{ .Values.application.secretChecksum }}"
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
        imagePullPolicy: {{ .Values.image.api.pullPolicy }}
        {{- if .Values.application.api.secrets }}
        envFrom:
        - secretRef:
            name: {{ .Values.application.api.secretName }}
        {{- end }}
        {{- with .Values.application.api.env }}
        {{- range $key, $val := . }}
        {{- if $val }}
          - name: "{{ tpl $key $  }}"
            value: "{{ tpl $val $  }}"
        {{- end }}
        {{- end }}
        {{- end }}

        ports:
        - name: "{{ .Values.service.api.name }}"
          containerPort: {{ .Values.service.api.internalPort }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.service.api.internalPort }}
            scheme: {{ .Values.livenessProbe.scheme }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.service.api.internalPort }}  
            scheme: {{ .Values.readinessProbe.scheme }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
        {{- end }}
        resources:
{{ toYaml .Values.resources.api | indent 12 }}
      {{- if .Values.hostAliases }}
      {{- with .Values.hostAliases }}
      hostAliases:
      {{- range $key, $val :=  . }}
      - ip: {{ $key }}
        hostnames:
        {{- range $hostname := $val }}
        - {{ $hostname }}
        {{- end -}}
      {{- end}}
      {{- end}}
      {{- end}}