{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- if .Values.service.api.url }}
    - {{ template "hostname" .Values.service.api.url }}
    {{- end }}
    secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "fullname" .)) }}
{{- end }}
  rules:
  - host: {{ template "hostname" .Values.service.api.url }}
    http:
      &httpRule
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.api.externalPort }}
  - host: ""
    http:
      &httpRule
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.api.externalPort }}
{{- end -}}
