openapi: 3.0.0

security:
  - BearerAuth: []

info:
  title: Glasswall File Rebuild Product API
  description: The Rebuild API provides developers the pathway to obtaining safe and secure files.
  version: 0.1.9
tags:
  - name: Rebuild
    description: Glasswall File Rebuild Product API
  - name: Analyse
    description: Glasswall Analyse Product API
  - name: FileTypeDetection
    description: Glasswall FileTypeDetection Product API        
servers:
  - url: http://91.109.25.70:8080
    description: esxi
paths:
  /api/rebuild/file:
    post:
      tags:
      - Rebuild
      summary: Rebuilds a file using its binary data
      description: <h3>Description:</h3>This endpoint accepts requests to rebuild a file with Glasswall d-FIRST™ Engine. File is sent in the request body with a 'Content-Type' of 'multipart/form-data'. The Rebuilt file is then returned in the response body with a 'Content-Type' of 'application/octet-stream'.
      parameters:
        - in: header
          name: Accept
          description: A value of 'application/octet-stream' will return the rebuilt file's binary content to the client.
          schema:
            type: string
            default: application/octet-stream
          required: false
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The binary contents of the selected file will be uploaded to the server.
              required:
                - file
            encoding:
              file:
                style: form
              contentManagementFlagJson:
                contentType: application/json
                style: form
      responses:
        '200':    # status code
          description: OK - The requested file was processed by the Glasswall d-FIRST™ Engine
          content: 
            application/octet-stream:
              schema:
                format: binary
                description: The body is a binary stream, containing the rebuilt file.
          headers:
            Content-Disposition:
              schema:
                type: string
              example: attachment; filename=ExampleFileName.pdf; filename*=UTF-8''ExampleFileName.pdf
              description: This contains the details of the rebuilt files binary data to download.
        '400':
          description: Bad Request - This is usually when the input is malformed or missing parameters
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CloudProxyResponseModel'
                  - $ref: '#/components/schemas/RequiredResponseModel'                  
        '415':
          $ref: '#/components/schemas/UnsupportedMediaType'
        '500':
          description: Internal Server Error - This is usually when something wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    description: "Error relating to the request"
                    items:
                      type: string                    
                  status:
                      type: string          
  /api/rebuild/base64:
    post:
      tags:
      - Rebuild    
      summary: Rebuilds a file using the Base64 encoded representation
      description: >
        This endpoint accepts requests to rebuild a file with Glasswall d-FIRST™ Engine.
        The request body contains the Base64 representation of the file with a 'Content-Type' of 'application/json'. 
        A Base64 Representation of the rebuilt file is then returned in the response with a 'Content-Type' of 'text/plain'.
        <br/><br/>
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              required:
                - Base64
              properties:
                Base64:
                  type: string
                  description: This is the Base64 encoded representation of the file to rebuild. 
            encoding:
              Base64:
                style: form
      responses:
        '200':    # status code
          description: OK - The requested Base64 was successfully decoded and processed by the Glasswall d-FIRST™ Engine
          content: 
            text/plain:
              schema:
                description: The body is a rebuilt file, Base64 encoded.
                type: string
                format: base64
                example: "0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAAAAAAAAAAAABAAAAUgAAAAAAAAAAEAAAAAAAAAEAAAD+////AAAAAFMAAAD//////////////////////////////..."
        '400':
          description: Bad Request - This is usually when the JSON input is malformed or missing parameters
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CloudProxyResponseModel'  
                  - $ref: '#/components/schemas/RequiredResponseModel'                                  
        '415':
          $ref: '#/components/schemas/UnsupportedMediaType' 
        '500':
          description: Internal Server Error - This is usually when something wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    description: "Error relating to the request"
                    items:
                      type: string                    
                  status:
                      type: string      
  /api/analyse/base64:
    post:
      tags:
      - Analyse    
      summary: Analyse a file using the Base64 encoded representation
      description: >
        This endpoint accepts requests to rebuild a file with Glasswall d-FIRST™ Engine.
        The request body contains the Base64 representation of the file with a 'Content-Type' of 'application/json'. 
        The Report file is then returned in the response body with a 'Content-Type' of 'application/octet-stream'.
        <br/><br/>
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              required:
                - Base64
              properties:
                Base64:
                  type: string
                  description: This is the Base64 encoded representation of the file to rebuild. 
            encoding:
              Base64:
                style: form
      responses:
        '200':    # status code
          description: OK - The requested file was processed by the Glasswall d-FIRST™ Engine
          content: 
            application/octet-stream:
              schema:
                format: binary
                description: The body is a binary stream, containing the report xml file.
          headers:
            Content-Disposition:
              schema:
                type: string
              example: attachment; filename=ExampleFileName.pdf; filename*=UTF-8''ExampleFileName.pdf
              description: This contains the details of the report xml file binary data to download.
        '400':
          description: Bad Request - This is usually when the JSON input is malformed or missing parameters
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CloudProxyResponseModel'
                  - $ref: '#/components/schemas/RequiredResponseModel'                  
        '415':
          $ref: '#/components/schemas/UnsupportedMediaType' 
        '500':
          description: Internal Server Error - This is usually when something wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    description: "Error relating to the request"
                    items:
                      type: string                    
                  status:
                      type: string
  /api/FileTypeDetection/base64:
    post:
      tags:
      - FileTypeDetection    
      summary: Detect a file type and other information using the Base64 encoded representation
      description: >
        This endpoint accepts requests to rebuild a file with Glasswall d-FIRST™ Engine.
        The request body contains the Base64 representation of the file with a 'Content-Type' of 'application/json'. 
        File information then returned in the response body with a 'Content-Type' of 'application/json'.
        <br/><br/>
      requestBody:
        content:
          "application/json":
            schema:
              type: object
              required:
                - Base64
              properties:
                Base64:
                  type: string
                  description: This is the Base64 encoded representation of the file to rebuild. 
            encoding:
              Base64:
                style: form
      responses:
        '200':    # status code
          description: OK - The requested file was processed by the Glasswall d-FIRST™ Engine
          content: 
            application/json:
              schema:
                description: The requested file was processed by the Glasswall d-FIRST™ Engine.
                type: object
                properties:
                  fileTypeName:
                    type: string
                    description: A value indicating file type.
                  fileSize:
                    type: number
                    description: A value indicating file size.
        '400':
          description: Bad Request - This is usually when the JSON input is malformed or missing parameters
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/CloudProxyResponseModel'
                  - $ref: '#/components/schemas/RequiredResponseModel'                  
        '415':
          $ref: '#/components/schemas/UnsupportedMediaType' 
        '500':
          description: Internal Server Error - This is usually when something wrong on the server.
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    description: "Error relating to the request"
                    items:
                      type: string                    
                  status:
                      type: string                                                   
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    UnsupportedMediaType:
      description: Unsupported Media Type - This happens when the request was not sent in JSON.
    CloudProxyResponseModel:
      description: Bad Request - This is usually when the JSON input is malformed.
      type: object
      properties:
        errors:
          type: array
          description: "Error relating to the request"
          items:
            type: string                    
        status:
            type: string       
    RequiredResponseModel:
      description: Bad Request - This is usually when parameters are missing.
      type: object
      properties:
        file:
          type: array
          description: "Error relating to the input file"
          items:
            type: string              