name: Build and Push cs-k8s-api

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "infra/kubernetes/*"
      - ".github/workflows/*"

env:
  DOCKER_REPO_NAME: glasswallsolutions
  GITHUB_SHA: ${{ github.sha }}
  

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name : Docker Login
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build -t cs-k8s-api --file Dockerfile .

      - name: Push image
        run: |
          IMAGE_TAG=$(echo $GITHUB_REF | cut -d'/' -f 3)-${GITHUB_SHA::7}
          docker image tag cs-k8s-api $DOCKER_REPO_NAME/cs-k8s-api:$IMAGE_TAG
          docker image tag cs-k8s-api $DOCKER_REPO_NAME/cs-k8s-api:latest
          docker push $DOCKER_REPO_NAME/cs-k8s-api:$IMAGE_TAG
          docker push $DOCKER_REPO_NAME/cs-k8s-api:latest
      
      - name: Update image tag in k8-rebuild repo
        run: |
          IMAGE_TAG=$(echo $GITHUB_REF | cut -d'/' -f 3)-${GITHUB_SHA::7}
          TARGET_BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)
          git config user.email github-actions@github.com
          git config user.name github-actions
          git checkout -b $IMAGE_TAG origin/${TARGET_BRANCH}
          # update imagestore selected tag value in the values.yaml file
          yq write infra/kubernetes/chart/values.yaml image.api.tag $IMAGE_TAG -i
          git add kubernetes/values.yaml
          git commit -m 'update image tag'
          git push origin $IMAGE_TAG
          # create a pull request from a new branch to target branch, merge the PR and delete the source branch.
          gh pr create --base ${TARGET_BRANCH} --title "Update ${{ env.IMAGESTORESELECTOR }} image tag to $IMAGE_TAG" --body ""
          sleep 5s
          gh pr merge $IMAGE_TAG -s
          git push origin --delete $IMAGE_TAG
          
        env:
          GITHUB_TOKEN: ${{ secrets.K8GITHUBTOKEN }}